# Generated by Django 3.2.23 on 2023-11-06 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('event_type', models.CharField(max_length=20)),
                ('gate_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_attendees', models.PositiveIntegerField()),
                ('current_attendees_count', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ticket_quantity', models.PositiveIntegerField(default=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
